# Generated by Django 4.0 on 2021-12-28 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('address', models.CharField(max_length=100, verbose_name='Endereço')),
                ('hospital', models.CharField(max_length=100, verbose_name='Hospital')),
                ('city', models.CharField(max_length=50, verbose_name='Cidade')),
                ('crm', models.CharField(max_length=30, verbose_name='CRM')),
                ('status', models.CharField(max_length=40, verbose_name='Situação')),
                ('obs', models.TextField(verbose_name='Observação')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='Data do cadastro')),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='Data do cadastro')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Número de telefone')),
                ('observation', models.TextField(verbose_name='Observação')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor', verbose_name='Médico')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doctors.specialty'),
        ),
    ]
