# Generated by Django 4.0 on 2021-12-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='crm',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='CRM'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='hospital',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Hospital'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='obs',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de telefone'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
    ]
